const books = [
  { BookId: 1, BookName: "The Silent Forest", Author: "R.K. Sharma", Price: 350, Pages: 220 },
  { BookId: 2, BookName: "Digital Dreams", Author: "Aman Verma", Price: 420, Pages: 310 },
  { BookId: 3, BookName: "Code Warriors", Author: "Neha Singh", Price: 500, Pages: 450 },
  { BookId: 4, BookName: "Mystery of Moon", Author: "Arjun Patel", Price: 280, Pages: 180 },
  { BookId: 5, BookName: "Ocean Deep", Author: "Sara Khan", Price: 390, Pages: 260 },
  { BookId: 6, BookName: "JavaScript Basics", Author: "Rahul Mehta", Price: 600, Pages: 520 },
  { BookId: 7, BookName: "Node.js Guide", Author: "Pooja Arora", Price: 650, Pages: 480 },
  { BookId: 8, BookName: "React in Action", Author: "Vikas Jain", Price: 720, Pages: 600 },
  { BookId: 9, BookName: "The Last Kingdom", Author: "Karan Malhotra", Price: 340, Pages: 240 },
  { BookId: 10, BookName: "Python Mastery", Author: "Deepak Yadav", Price: 800, Pages: 700 },

  { BookId: 11, BookName: "Machine Learning", Author: "Anjali Gupta", Price: 950, Pages: 850 },
  { BookId: 12, BookName: "Cloud Computing", Author: "Ravi Sinha", Price: 670, Pages: 540 },
  { BookId: 13, BookName: "AI Revolution", Author: "Simran Kaur", Price: 780, Pages: 620 },
  { BookId: 14, BookName: "Cyber Security", Author: "Mohit Agarwal", Price: 890, Pages: 710 },
  { BookId: 15, BookName: "Data Structures", Author: "Priya Nair", Price: 550, Pages: 430 },
  { BookId: 16, BookName: "Algorithms Unlocked", Author: "Sandeep Roy", Price: 620, Pages: 500 },
  { BookId: 17, BookName: "Networking Essentials", Author: "Manish Tiwari", Price: 470, Pages: 390 },
  { BookId: 18, BookName: "Database Systems", Author: "Kriti Joshi", Price: 710, Pages: 610 },
  { BookId: 19, BookName: "Operating Systems", Author: "Nitin Arora", Price: 680, Pages: 560 },
  { BookId: 20, BookName: "Web Development", Author: "Farhan Ali", Price: 530, Pages: 450 },

  { BookId: 21, BookName: "The Hidden Truth", Author: "Aisha Khan", Price: 300, Pages: 200 },
  { BookId: 22, BookName: "Journey to Mars", Author: "Rajeev Kumar", Price: 410, Pages: 320 },
  { BookId: 23, BookName: "Life of Pi", Author: "Yash Chopra", Price: 360, Pages: 270 },
  { BookId: 24, BookName: "The Dark Night", Author: "Abhishek Das", Price: 290, Pages: 210 },
  { BookId: 25, BookName: "Startup Success", Author: "Rohan Kapoor", Price: 580, Pages: 490 },
  { BookId: 26, BookName: "Business Growth", Author: "Sneha Bansal", Price: 610, Pages: 530 },
  { BookId: 27, BookName: "Marketing 101", Author: "Akash Mittal", Price: 450, Pages: 340 },
  { BookId: 28, BookName: "Finance Basics", Author: "Nidhi Arora", Price: 520, Pages: 410 },
  { BookId: 29, BookName: "Economics Today", Author: "Harsh Gupta", Price: 480, Pages: 370 },
  { BookId: 30, BookName: "World History", Author: "Meera Iyer", Price: 390, Pages: 290 },

  { BookId: 31, BookName: "Ancient Civilizations", Author: "Tarun Mishra", Price: 430, Pages: 350 },
  { BookId: 32, BookName: "Physics Simplified", Author: "Aditya Rao", Price: 570, Pages: 470 },
  { BookId: 33, BookName: "Chemistry Concepts", Author: "Pallavi Sen", Price: 490, Pages: 380 },
  { BookId: 34, BookName: "Mathematics Genius", Author: "Ritesh Dubey", Price: 640, Pages: 590 },
  { BookId: 35, BookName: "Biology Today", Author: "Isha Kapoor", Price: 510, Pages: 420 },
  { BookId: 36, BookName: "Space Exploration", Author: "Kabir Singh", Price: 730, Pages: 650 },
  { BookId: 37, BookName: "Astronomy Facts", Author: "Lavanya Pillai", Price: 690, Pages: 570 },
  { BookId: 38, BookName: "The Great War", Author: "Faiz Ahmed", Price: 440, Pages: 360 },
  { BookId: 39, BookName: "Modern India", Author: "Dev Malhotra", Price: 350, Pages: 250 },
  { BookId: 40, BookName: "Indian Culture", Author: "Renu Sharma", Price: 460, Pages: 390 },

  { BookId: 41, BookName: "Creative Writing", Author: "Ankit Saxena", Price: 390, Pages: 300 },
  { BookId: 42, BookName: "Poetry Collection", Author: "Shalini Roy", Price: 320, Pages: 190 },
  { BookId: 43, BookName: "English Grammar", Author: "Jyoti Sharma", Price: 280, Pages: 230 },
  { BookId: 44, BookName: "Spoken English", Author: "Rajat Khanna", Price: 340, Pages: 260 },
  { BookId: 45, BookName: "Personality Development", Author: "Naveen Joshi", Price: 540, Pages: 440 },
  { BookId: 46, BookName: "Time Management", Author: "Sahil Arora", Price: 400, Pages: 310 },
  { BookId: 47, BookName: "Leadership Skills", Author: "Muskan Jain", Price: 620, Pages: 520 },
  { BookId: 48, BookName: "Public Speaking", Author: "Aditi Sharma", Price: 470, Pages: 350 },
  { BookId: 49, BookName: "Mind Power", Author: "Kunal Verma", Price: 510, Pages: 430 },
  { BookId: 50, BookName: "Success Habits", Author: "Tanya Gupta", Price: 580, Pages: 500 }
];

module.exports = books;